// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: ddns.proto

package ddns_go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DdnsService_GetNodes_FullMethodName          = "/DdnsService/GetNodes"
	DdnsService_GetDomainList_FullMethodName     = "/DdnsService/GetDomainList"
	DdnsService_FetchDomain_FullMethodName       = "/DdnsService/FetchDomain"
	DdnsService_AnnounceDomain_FullMethodName    = "/DdnsService/AnnounceDomain"
	DdnsService_OutdatedDomain_FullMethodName    = "/DdnsService/OutdatedDomain"
	DdnsService_AnnounceID_FullMethodName        = "/DdnsService/AnnounceID"
	DdnsService_GetID_FullMethodName             = "/DdnsService/GetID"
	DdnsService_UpdateDomainBlock_FullMethodName = "/DdnsService/UpdateDomainBlock"
	DdnsService_PeersKnown_FullMethodName        = "/DdnsService/PeersKnown"
)

// DdnsServiceClient is the client API for DdnsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DdnsServiceClient interface {
	GetNodes(ctx context.Context, in *AskNodes, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Nodes], error)
	GetDomainList(ctx context.Context, in *Ask, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Domain], error)
	FetchDomain(ctx context.Context, in *Domain, opts ...grpc.CallOption) (*DomainBlock, error)
	AnnounceDomain(ctx context.Context, in *DomainBlock, opts ...grpc.CallOption) (*Confirmation, error)
	OutdatedDomain(ctx context.Context, in *Domain, opts ...grpc.CallOption) (*Confirmation, error)
	AnnounceID(ctx context.Context, in *PeerID, opts ...grpc.CallOption) (*Confirmation, error)
	GetID(ctx context.Context, in *Ask, opts ...grpc.CallOption) (*PeerID, error)
	UpdateDomainBlock(ctx context.Context, in *UpdatedDomainBlock, opts ...grpc.CallOption) (*Confirmation, error)
	PeersKnown(ctx context.Context, in *Ask, opts ...grpc.CallOption) (*NumOfPeersKnown, error)
}

type ddnsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDdnsServiceClient(cc grpc.ClientConnInterface) DdnsServiceClient {
	return &ddnsServiceClient{cc}
}

func (c *ddnsServiceClient) GetNodes(ctx context.Context, in *AskNodes, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Nodes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DdnsService_ServiceDesc.Streams[0], DdnsService_GetNodes_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AskNodes, Nodes]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DdnsService_GetNodesClient = grpc.ServerStreamingClient[Nodes]

func (c *ddnsServiceClient) GetDomainList(ctx context.Context, in *Ask, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Domain], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DdnsService_ServiceDesc.Streams[1], DdnsService_GetDomainList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Ask, Domain]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DdnsService_GetDomainListClient = grpc.ServerStreamingClient[Domain]

func (c *ddnsServiceClient) FetchDomain(ctx context.Context, in *Domain, opts ...grpc.CallOption) (*DomainBlock, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DomainBlock)
	err := c.cc.Invoke(ctx, DdnsService_FetchDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ddnsServiceClient) AnnounceDomain(ctx context.Context, in *DomainBlock, opts ...grpc.CallOption) (*Confirmation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, DdnsService_AnnounceDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ddnsServiceClient) OutdatedDomain(ctx context.Context, in *Domain, opts ...grpc.CallOption) (*Confirmation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, DdnsService_OutdatedDomain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ddnsServiceClient) AnnounceID(ctx context.Context, in *PeerID, opts ...grpc.CallOption) (*Confirmation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, DdnsService_AnnounceID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ddnsServiceClient) GetID(ctx context.Context, in *Ask, opts ...grpc.CallOption) (*PeerID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PeerID)
	err := c.cc.Invoke(ctx, DdnsService_GetID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ddnsServiceClient) UpdateDomainBlock(ctx context.Context, in *UpdatedDomainBlock, opts ...grpc.CallOption) (*Confirmation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Confirmation)
	err := c.cc.Invoke(ctx, DdnsService_UpdateDomainBlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ddnsServiceClient) PeersKnown(ctx context.Context, in *Ask, opts ...grpc.CallOption) (*NumOfPeersKnown, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NumOfPeersKnown)
	err := c.cc.Invoke(ctx, DdnsService_PeersKnown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DdnsServiceServer is the server API for DdnsService service.
// All implementations must embed UnimplementedDdnsServiceServer
// for forward compatibility.
type DdnsServiceServer interface {
	GetNodes(*AskNodes, grpc.ServerStreamingServer[Nodes]) error
	GetDomainList(*Ask, grpc.ServerStreamingServer[Domain]) error
	FetchDomain(context.Context, *Domain) (*DomainBlock, error)
	AnnounceDomain(context.Context, *DomainBlock) (*Confirmation, error)
	OutdatedDomain(context.Context, *Domain) (*Confirmation, error)
	AnnounceID(context.Context, *PeerID) (*Confirmation, error)
	GetID(context.Context, *Ask) (*PeerID, error)
	UpdateDomainBlock(context.Context, *UpdatedDomainBlock) (*Confirmation, error)
	PeersKnown(context.Context, *Ask) (*NumOfPeersKnown, error)
	mustEmbedUnimplementedDdnsServiceServer()
}

// UnimplementedDdnsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDdnsServiceServer struct{}

func (UnimplementedDdnsServiceServer) GetNodes(*AskNodes, grpc.ServerStreamingServer[Nodes]) error {
	return status.Error(codes.Unimplemented, "method GetNodes not implemented")
}
func (UnimplementedDdnsServiceServer) GetDomainList(*Ask, grpc.ServerStreamingServer[Domain]) error {
	return status.Error(codes.Unimplemented, "method GetDomainList not implemented")
}
func (UnimplementedDdnsServiceServer) FetchDomain(context.Context, *Domain) (*DomainBlock, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchDomain not implemented")
}
func (UnimplementedDdnsServiceServer) AnnounceDomain(context.Context, *DomainBlock) (*Confirmation, error) {
	return nil, status.Error(codes.Unimplemented, "method AnnounceDomain not implemented")
}
func (UnimplementedDdnsServiceServer) OutdatedDomain(context.Context, *Domain) (*Confirmation, error) {
	return nil, status.Error(codes.Unimplemented, "method OutdatedDomain not implemented")
}
func (UnimplementedDdnsServiceServer) AnnounceID(context.Context, *PeerID) (*Confirmation, error) {
	return nil, status.Error(codes.Unimplemented, "method AnnounceID not implemented")
}
func (UnimplementedDdnsServiceServer) GetID(context.Context, *Ask) (*PeerID, error) {
	return nil, status.Error(codes.Unimplemented, "method GetID not implemented")
}
func (UnimplementedDdnsServiceServer) UpdateDomainBlock(context.Context, *UpdatedDomainBlock) (*Confirmation, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDomainBlock not implemented")
}
func (UnimplementedDdnsServiceServer) PeersKnown(context.Context, *Ask) (*NumOfPeersKnown, error) {
	return nil, status.Error(codes.Unimplemented, "method PeersKnown not implemented")
}
func (UnimplementedDdnsServiceServer) mustEmbedUnimplementedDdnsServiceServer() {}
func (UnimplementedDdnsServiceServer) testEmbeddedByValue()                     {}

// UnsafeDdnsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DdnsServiceServer will
// result in compilation errors.
type UnsafeDdnsServiceServer interface {
	mustEmbedUnimplementedDdnsServiceServer()
}

func RegisterDdnsServiceServer(s grpc.ServiceRegistrar, srv DdnsServiceServer) {
	// If the following call panics, it indicates UnimplementedDdnsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DdnsService_ServiceDesc, srv)
}

func _DdnsService_GetNodes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AskNodes)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DdnsServiceServer).GetNodes(m, &grpc.GenericServerStream[AskNodes, Nodes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DdnsService_GetNodesServer = grpc.ServerStreamingServer[Nodes]

func _DdnsService_GetDomainList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Ask)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DdnsServiceServer).GetDomainList(m, &grpc.GenericServerStream[Ask, Domain]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DdnsService_GetDomainListServer = grpc.ServerStreamingServer[Domain]

func _DdnsService_FetchDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Domain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DdnsServiceServer).FetchDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DdnsService_FetchDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DdnsServiceServer).FetchDomain(ctx, req.(*Domain))
	}
	return interceptor(ctx, in, info, handler)
}

func _DdnsService_AnnounceDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DomainBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DdnsServiceServer).AnnounceDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DdnsService_AnnounceDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DdnsServiceServer).AnnounceDomain(ctx, req.(*DomainBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _DdnsService_OutdatedDomain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Domain)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DdnsServiceServer).OutdatedDomain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DdnsService_OutdatedDomain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DdnsServiceServer).OutdatedDomain(ctx, req.(*Domain))
	}
	return interceptor(ctx, in, info, handler)
}

func _DdnsService_AnnounceID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PeerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DdnsServiceServer).AnnounceID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DdnsService_AnnounceID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DdnsServiceServer).AnnounceID(ctx, req.(*PeerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DdnsService_GetID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DdnsServiceServer).GetID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DdnsService_GetID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DdnsServiceServer).GetID(ctx, req.(*Ask))
	}
	return interceptor(ctx, in, info, handler)
}

func _DdnsService_UpdateDomainBlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatedDomainBlock)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DdnsServiceServer).UpdateDomainBlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DdnsService_UpdateDomainBlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DdnsServiceServer).UpdateDomainBlock(ctx, req.(*UpdatedDomainBlock))
	}
	return interceptor(ctx, in, info, handler)
}

func _DdnsService_PeersKnown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ask)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DdnsServiceServer).PeersKnown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DdnsService_PeersKnown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DdnsServiceServer).PeersKnown(ctx, req.(*Ask))
	}
	return interceptor(ctx, in, info, handler)
}

// DdnsService_ServiceDesc is the grpc.ServiceDesc for DdnsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DdnsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DdnsService",
	HandlerType: (*DdnsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchDomain",
			Handler:    _DdnsService_FetchDomain_Handler,
		},
		{
			MethodName: "AnnounceDomain",
			Handler:    _DdnsService_AnnounceDomain_Handler,
		},
		{
			MethodName: "OutdatedDomain",
			Handler:    _DdnsService_OutdatedDomain_Handler,
		},
		{
			MethodName: "AnnounceID",
			Handler:    _DdnsService_AnnounceID_Handler,
		},
		{
			MethodName: "GetID",
			Handler:    _DdnsService_GetID_Handler,
		},
		{
			MethodName: "UpdateDomainBlock",
			Handler:    _DdnsService_UpdateDomainBlock_Handler,
		},
		{
			MethodName: "PeersKnown",
			Handler:    _DdnsService_PeersKnown_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetNodes",
			Handler:       _DdnsService_GetNodes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetDomainList",
			Handler:       _DdnsService_GetDomainList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ddns.proto",
}
