// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: ddns.proto

package ddns_go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ask           bool                   `protobuf:"varint,1,opt,name=ask,proto3" json:"ask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ask) Reset() {
	*x = Ask{}
	mi := &file_ddns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ask) ProtoMessage() {}

func (x *Ask) ProtoReflect() protoreflect.Message {
	mi := &file_ddns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ask.ProtoReflect.Descriptor instead.
func (*Ask) Descriptor() ([]byte, []int) {
	return file_ddns_proto_rawDescGZIP(), []int{0}
}

func (x *Ask) GetAsk() bool {
	if x != nil {
		return x.Ask
	}
	return false
}

type Confirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirmation) Reset() {
	*x = Confirmation{}
	mi := &file_ddns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation) ProtoMessage() {}

func (x *Confirmation) ProtoReflect() protoreflect.Message {
	mi := &file_ddns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation.ProtoReflect.Descriptor instead.
func (*Confirmation) Descriptor() ([]byte, []int) {
	return file_ddns_proto_rawDescGZIP(), []int{1}
}

func (x *Confirmation) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Confirmation) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type AskNodes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NumberOfNodes uint32                 `protobuf:"varint,1,opt,name=numberOfNodes,proto3" json:"numberOfNodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AskNodes) Reset() {
	*x = AskNodes{}
	mi := &file_ddns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AskNodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AskNodes) ProtoMessage() {}

func (x *AskNodes) ProtoReflect() protoreflect.Message {
	mi := &file_ddns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AskNodes.ProtoReflect.Descriptor instead.
func (*AskNodes) Descriptor() ([]byte, []int) {
	return file_ddns_proto_rawDescGZIP(), []int{2}
}

func (x *AskNodes) GetNumberOfNodes() uint32 {
	if x != nil {
		return x.NumberOfNodes
	}
	return 0
}

type Nodes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Nodes_Ip
	//	*Nodes_Error
	Message       isNodes_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Nodes) Reset() {
	*x = Nodes{}
	mi := &file_ddns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Nodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Nodes) ProtoMessage() {}

func (x *Nodes) ProtoReflect() protoreflect.Message {
	mi := &file_ddns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Nodes.ProtoReflect.Descriptor instead.
func (*Nodes) Descriptor() ([]byte, []int) {
	return file_ddns_proto_rawDescGZIP(), []int{3}
}

func (x *Nodes) GetMessage() isNodes_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Nodes) GetIp() string {
	if x != nil {
		if x, ok := x.Message.(*Nodes_Ip); ok {
			return x.Ip
		}
	}
	return ""
}

func (x *Nodes) GetError() string {
	if x != nil {
		if x, ok := x.Message.(*Nodes_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isNodes_Message interface {
	isNodes_Message()
}

type Nodes_Ip struct {
	Ip string `protobuf:"bytes,1,opt,name=ip,proto3,oneof"`
}

type Nodes_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*Nodes_Ip) isNodes_Message() {}

func (*Nodes_Error) isNodes_Message() {}

type Domain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	Hash          string                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_ddns_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_ddns_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_ddns_proto_rawDescGZIP(), []int{4}
}

func (x *Domain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Domain) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type PeerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerID) Reset() {
	*x = PeerID{}
	mi := &file_ddns_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerID) ProtoMessage() {}

func (x *PeerID) ProtoReflect() protoreflect.Message {
	mi := &file_ddns_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerID.ProtoReflect.Descriptor instead.
func (*PeerID) Descriptor() ([]byte, []int) {
	return file_ddns_proto_rawDescGZIP(), []int{5}
}

func (x *PeerID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Blockheaders struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Nonce         uint32                 `protobuf:"varint,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Target        uint32                 `protobuf:"varint,3,opt,name=target,proto3" json:"target,omitempty"`
	DomainName    string                 `protobuf:"bytes,4,opt,name=domainName,proto3" json:"domainName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Blockheaders) Reset() {
	*x = Blockheaders{}
	mi := &file_ddns_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Blockheaders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Blockheaders) ProtoMessage() {}

func (x *Blockheaders) ProtoReflect() protoreflect.Message {
	mi := &file_ddns_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Blockheaders.ProtoReflect.Descriptor instead.
func (*Blockheaders) Descriptor() ([]byte, []int) {
	return file_ddns_proto_rawDescGZIP(), []int{6}
}

func (x *Blockheaders) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Blockheaders) GetNonce() uint32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Blockheaders) GetTarget() uint32 {
	if x != nil {
		return x.Target
	}
	return 0
}

func (x *Blockheaders) GetDomainName() string {
	if x != nil {
		return x.DomainName
	}
	return ""
}

type DomainBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blockheaders  *Blockheaders          `protobuf:"bytes,1,opt,name=blockheaders,proto3" json:"blockheaders,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Records       *string                `protobuf:"bytes,3,opt,name=records,proto3,oneof" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainBlock) Reset() {
	*x = DomainBlock{}
	mi := &file_ddns_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainBlock) ProtoMessage() {}

func (x *DomainBlock) ProtoReflect() protoreflect.Message {
	mi := &file_ddns_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainBlock.ProtoReflect.Descriptor instead.
func (*DomainBlock) Descriptor() ([]byte, []int) {
	return file_ddns_proto_rawDescGZIP(), []int{7}
}

func (x *DomainBlock) GetBlockheaders() *Blockheaders {
	if x != nil {
		return x.Blockheaders
	}
	return nil
}

func (x *DomainBlock) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *DomainBlock) GetRecords() string {
	if x != nil && x.Records != nil {
		return *x.Records
	}
	return ""
}

type UpdatedDomainBlock struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CurrentDomainBlock *DomainBlock           `protobuf:"bytes,1,opt,name=currentDomainBlock,proto3" json:"currentDomainBlock,omitempty"`
	UpdateDomainBlock  *DomainBlock           `protobuf:"bytes,2,opt,name=updateDomainBlock,proto3" json:"updateDomainBlock,omitempty"`
	SignedHash         string                 `protobuf:"bytes,3,opt,name=signedHash,proto3" json:"signedHash,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdatedDomainBlock) Reset() {
	*x = UpdatedDomainBlock{}
	mi := &file_ddns_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatedDomainBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatedDomainBlock) ProtoMessage() {}

func (x *UpdatedDomainBlock) ProtoReflect() protoreflect.Message {
	mi := &file_ddns_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatedDomainBlock.ProtoReflect.Descriptor instead.
func (*UpdatedDomainBlock) Descriptor() ([]byte, []int) {
	return file_ddns_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatedDomainBlock) GetCurrentDomainBlock() *DomainBlock {
	if x != nil {
		return x.CurrentDomainBlock
	}
	return nil
}

func (x *UpdatedDomainBlock) GetUpdateDomainBlock() *DomainBlock {
	if x != nil {
		return x.UpdateDomainBlock
	}
	return nil
}

func (x *UpdatedDomainBlock) GetSignedHash() string {
	if x != nil {
		return x.SignedHash
	}
	return ""
}

type NumOfPeersKnown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Num           uint32                 `protobuf:"varint,1,opt,name=num,proto3" json:"num,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumOfPeersKnown) Reset() {
	*x = NumOfPeersKnown{}
	mi := &file_ddns_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumOfPeersKnown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumOfPeersKnown) ProtoMessage() {}

func (x *NumOfPeersKnown) ProtoReflect() protoreflect.Message {
	mi := &file_ddns_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumOfPeersKnown.ProtoReflect.Descriptor instead.
func (*NumOfPeersKnown) Descriptor() ([]byte, []int) {
	return file_ddns_proto_rawDescGZIP(), []int{9}
}

func (x *NumOfPeersKnown) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

var File_ddns_proto protoreflect.FileDescriptor

const file_ddns_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"ddns.proto\"\x17\n" +
	"\x03Ask\x12\x10\n" +
	"\x03ask\x18\x01 \x01(\bR\x03ask\"M\n" +
	"\fConfirmation\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"0\n" +
	"\bAskNodes\x12$\n" +
	"\rnumberOfNodes\x18\x01 \x01(\rR\rnumberOfNodes\"<\n" +
	"\x05Nodes\x12\x10\n" +
	"\x02ip\x18\x01 \x01(\tH\x00R\x02ip\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\t\n" +
	"\amessage\"4\n" +
	"\x06Domain\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\"\x18\n" +
	"\x06PeerID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"z\n" +
	"\fBlockheaders\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\rR\x05nonce\x12\x16\n" +
	"\x06target\x18\x03 \x01(\rR\x06target\x12\x1e\n" +
	"\n" +
	"domainName\x18\x04 \x01(\tR\n" +
	"domainName\"\x89\x01\n" +
	"\vDomainBlock\x121\n" +
	"\fblockheaders\x18\x01 \x01(\v2\r.BlockheadersR\fblockheaders\x12\x1c\n" +
	"\tpublicKey\x18\x02 \x01(\tR\tpublicKey\x12\x1d\n" +
	"\arecords\x18\x03 \x01(\tH\x00R\arecords\x88\x01\x01B\n" +
	"\n" +
	"\b_records\"\xae\x01\n" +
	"\x12UpdatedDomainBlock\x12<\n" +
	"\x12currentDomainBlock\x18\x01 \x01(\v2\f.DomainBlockR\x12currentDomainBlock\x12:\n" +
	"\x11updateDomainBlock\x18\x02 \x01(\v2\f.DomainBlockR\x11updateDomainBlock\x12\x1e\n" +
	"\n" +
	"signedHash\x18\x03 \x01(\tR\n" +
	"signedHash\"#\n" +
	"\x0fNumOfPeersKnown\x12\x10\n" +
	"\x03num\x18\x01 \x01(\rR\x03num2\xfe\x02\n" +
	"\vDdnsService\x12!\n" +
	"\bGetNodes\x12\t.AskNodes\x1a\x06.Nodes\"\x000\x01\x12\"\n" +
	"\rGetDomainList\x12\x04.Ask\x1a\a.Domain\"\x000\x01\x12&\n" +
	"\vFetchDomain\x12\a.Domain\x1a\f.DomainBlock\"\x00\x12/\n" +
	"\x0eAnnounceDomain\x12\f.DomainBlock\x1a\r.Confirmation\"\x00\x12*\n" +
	"\x0eOutdatedDomain\x12\a.Domain\x1a\r.Confirmation\"\x00\x12&\n" +
	"\n" +
	"AnnounceID\x12\a.PeerID\x1a\r.Confirmation\"\x00\x12\x18\n" +
	"\x05GetID\x12\x04.Ask\x1a\a.PeerID\"\x00\x129\n" +
	"\x11UpdateDomainBlock\x12\x13.UpdatedDomainBlock\x1a\r.Confirmation\"\x00\x12&\n" +
	"\n" +
	"PeersKnown\x12\x04.Ask\x1a\x10.NumOfPeersKnown\"\x00B Z\x1egithub.com/doctor112-1/ddns-gob\x06proto3"

var (
	file_ddns_proto_rawDescOnce sync.Once
	file_ddns_proto_rawDescData []byte
)

func file_ddns_proto_rawDescGZIP() []byte {
	file_ddns_proto_rawDescOnce.Do(func() {
		file_ddns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ddns_proto_rawDesc), len(file_ddns_proto_rawDesc)))
	})
	return file_ddns_proto_rawDescData
}

var file_ddns_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_ddns_proto_goTypes = []any{
	(*Ask)(nil),                // 0: Ask
	(*Confirmation)(nil),       // 1: Confirmation
	(*AskNodes)(nil),           // 2: AskNodes
	(*Nodes)(nil),              // 3: Nodes
	(*Domain)(nil),             // 4: Domain
	(*PeerID)(nil),             // 5: PeerID
	(*Blockheaders)(nil),       // 6: Blockheaders
	(*DomainBlock)(nil),        // 7: DomainBlock
	(*UpdatedDomainBlock)(nil), // 8: UpdatedDomainBlock
	(*NumOfPeersKnown)(nil),    // 9: NumOfPeersKnown
}
var file_ddns_proto_depIdxs = []int32{
	6,  // 0: DomainBlock.blockheaders:type_name -> Blockheaders
	7,  // 1: UpdatedDomainBlock.currentDomainBlock:type_name -> DomainBlock
	7,  // 2: UpdatedDomainBlock.updateDomainBlock:type_name -> DomainBlock
	2,  // 3: DdnsService.GetNodes:input_type -> AskNodes
	0,  // 4: DdnsService.GetDomainList:input_type -> Ask
	4,  // 5: DdnsService.FetchDomain:input_type -> Domain
	7,  // 6: DdnsService.AnnounceDomain:input_type -> DomainBlock
	4,  // 7: DdnsService.OutdatedDomain:input_type -> Domain
	5,  // 8: DdnsService.AnnounceID:input_type -> PeerID
	0,  // 9: DdnsService.GetID:input_type -> Ask
	8,  // 10: DdnsService.UpdateDomainBlock:input_type -> UpdatedDomainBlock
	0,  // 11: DdnsService.PeersKnown:input_type -> Ask
	3,  // 12: DdnsService.GetNodes:output_type -> Nodes
	4,  // 13: DdnsService.GetDomainList:output_type -> Domain
	7,  // 14: DdnsService.FetchDomain:output_type -> DomainBlock
	1,  // 15: DdnsService.AnnounceDomain:output_type -> Confirmation
	1,  // 16: DdnsService.OutdatedDomain:output_type -> Confirmation
	1,  // 17: DdnsService.AnnounceID:output_type -> Confirmation
	5,  // 18: DdnsService.GetID:output_type -> PeerID
	1,  // 19: DdnsService.UpdateDomainBlock:output_type -> Confirmation
	9,  // 20: DdnsService.PeersKnown:output_type -> NumOfPeersKnown
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_ddns_proto_init() }
func file_ddns_proto_init() {
	if File_ddns_proto != nil {
		return
	}
	file_ddns_proto_msgTypes[1].OneofWrappers = []any{}
	file_ddns_proto_msgTypes[3].OneofWrappers = []any{
		(*Nodes_Ip)(nil),
		(*Nodes_Error)(nil),
	}
	file_ddns_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ddns_proto_rawDesc), len(file_ddns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ddns_proto_goTypes,
		DependencyIndexes: file_ddns_proto_depIdxs,
		MessageInfos:      file_ddns_proto_msgTypes,
	}.Build()
	File_ddns_proto = out.File
	file_ddns_proto_goTypes = nil
	file_ddns_proto_depIdxs = nil
}
